language: ruby
bundler_args: --jobs 3 --retry 3
sudo: false
script: "bundle exec rspec spec"
before_install:
  - "rm ${BUNDLE_GEMFILE}.lock"
before_script:
  - "RAILS_ENV=test bundle update"
  - "RAILS_ENV=test bundle exec rails db:drop db:create db:migrate db:seed --trace"
